server:
  port : 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data: classpath:/test.sql
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver